FIND_PATH( MYSQL_INCLUDE_DIR mysql.h
     ${MYSQL_ROOT_PATH}/include
)

IF(WIN32)
FIND_LIBRARY( MYSQL_mysql_LIBRARY libmysql
      ${MYSQL_ROOT_PATH}/lib
)
ELSE(WIN32)
FIND_LIBRARY( MYSQL_mysql_LIBRARY mysqlclient
	${MYSQL_ROOT_PATH}/lib
)
FIND_LIBRARY( MYSQL_mygcc_LIBRARY mygcc
	${MYSQL_ROOT_PATH}/lib
)
FIND_LIBRARY( MYSQL_z_LIBRARY z
	${MYSQL_ROOT_PATH}/lib
)
ENDIF(WIN32)
SET(MYSQL_LIBRARIES ${MYSQL_mysql_LIBRARY} ${MYSQL_z_LIBRARY} ${MYSQL_mygcc_LIBRARY})



